import type { Metadata } from "next";
import { Inter, Kumbh_Sans } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/providers/theme-provider";
import Navbar from "@/components/Navbar/Navbar";
import { cn } from "@/lib/utils";
import ToastProvider from "@/providers/toast-provider";
import SessionProvider from "@/providers/session-provider";

const font = Kumbh_Sans({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata: Metadata = {
  title: "E-commerce product page",
  description: "E-commerce product page Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={cn(font.className, "h-full")}>
        <SessionProvider>
          <ThemeProvider attribute="class" enableSystem defaultTheme="light">
            <ToastProvider />
            {children}
          </ThemeProvider>
        </SessionProvider>
      </body>
    </html>
  );
}
