import type { Metadata } from "next";
import { Inter, Kumbh_Sans } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/providers/theme-provider";
import Navbar from "@/components/Navbar/Navbar";
import { cn } from "@/lib/utils";
import ToastProvider from "@/providers/toast-provider";

const font = Kumbh_Sans({
  subsets: ["latin"],
  variable: "--font-sans",
  weight: ["400", "700"],
});

export const metadata: Metadata = {
  title: "E-commerce product page",
  description: "E-commerce product page Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={cn(font.className, "h-full flex flex-col")}
        suppressHydrationWarning
      >
        <ThemeProvider attribute="class" enableSystem defaultTheme="light">
          <ToastProvider />
          <Navbar />
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
